namespace Messaging.MSMQ
{
    public class Constants
    {
        public enum MessageActionType
        {
            NoMessage = -1,
            UpdatedUserDefinedUnit = 0,
            UpdatedProductSet = 1,
            UpdatedPriceBand = 2,
            UpdatedGroup = 3,
            UpdatedProductCost = 4,
            GlobalUpdate = 5,
            UpdatedProductNutrient = 6,
            UpdatedProductIntolerance = 7,
            UpdatedProductNutrientInclusive = 8,
            GlobalUpdateBudgeted = 9,
            UpdateAlternateIngredients = 10,
            CreatePackage = 11,
            StarChefEventsUpdated = 12,
            UpdatedUser = 13
        }
        public enum EntityType
        {
            NotSet = -1,
            User = 10,
            UserGroup = 11,
            Group = 12,
            Ingredient = 20,
            Dish = 21,
            Menu = 22,
            Supplier = 23,
            UserUnit = 24,
            Category = 25,
            SuppliedDish = 26,
            Document = 28,
            Package = 29,
            IngredientCostPrice = 32,
            DishDetails = 35,
            DishPricing = 36,
            DishAdvancedNutrition = 38,
            Manufacturer = 40,
            Nutrition = 50,
            GroupFilter = 120,
            BasicReports = 130,
            StandardReports = 131,
            AdvancedReports = 132,
            AdminReports = 133,
            PriceBand = 135,
            PriceBandOverride = 136,
            UserPreferences = 137,
            MenuCycle = 138,
            UserLogin = 139,
            ListManager = 140,
            ProductSet = 170,
            MenuSet = 171,
            MenuPeriod = 172,
            IngredientCostManagement = 210,
            GlobalSearchReplace = 219,
            GroupManagement = 220,
            DbSettings = 221,
            DataManagement = 222,
            PricingManagement = 223,
            SystemDelete = 224,
            AllowReplaceRemoveRecs = 225,
            PriceBandManagement = 227,
            DlineLookup = 228,
            MasterListExportMangement = 229,
            InterfaceManagerManagement = 230,
            BudgetedCostManagement = 240,
            ProductSpecificationManagement = 250,
            IngredientImport = 251,
            SetManagement = 252,
            MealPeriodManagement = 253,
            StarChefLiteManagement = 255
        }
    }
}
